import type {Metadata, Viewport} from "next";
import {Inter, Nabla} from "next/font/google";
import "./globals.css";
import Header from "@/app/_component/layout/header";
import NavigationBar from "@/app/_component/layout/navigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <NavigationBar/>
      </body>
    </html>
  );
}
